name = "chrypnotoad-website"
type = "webpack"
workers_dev = true
route = "chrypnotoad.com/*"

[site]
bucket = "./www"
entry-point = "workers-site"

[env.toad]
workers_dev = true
route = "toad.chrypnotoad.com/*"
bucket = "./toad"

[env.nft]
workers_dev = true
route = "nft.chrypnotoad.com/*"
bucket = "./nft"